=== hoenir-space/hoenir-core/example/0.0.1/xsd/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://hoenir.space/resource/schema/data" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="data" type="data:dataType" xmlns:data="https://hoenir.space/resource/schema/data"/>
  <xs:simpleType name="UUIDType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="baseType">
    <xs:simpleContent>
      <xs:extension base="data:UUIDType" xmlns:data="https://hoenir.space/resource/schema/data">
        <xs:attribute type="data:UUIDType" name="type" xmlns:data="https://hoenir.space/resource/schema/data"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="idType">
    <xs:simpleContent>
      <xs:extension base="data:UUIDType" xmlns:data="https://hoenir.space/resource/schema/data">
        <xs:attribute type="data:UUIDType" name="type" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="targetType">
    <xs:simpleContent>
      <xs:extension base="data:UUIDType" xmlns:data="https://hoenir.space/resource/schema/data">
        <xs:attribute type="data:UUIDType" name="type" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="weightType">
    <xs:sequence>
      <xs:element type="data:idType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="xs:float" name="value" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="weightsType">
    <xs:sequence>
      <xs:element type="data:weightType" name="weight" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="edgeType">
    <xs:sequence>
      <xs:element type="data:idType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:targetType" name="target" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:weightsType" name="weights" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="edgesType">
    <xs:sequence>
      <xs:element type="data:edgeType" name="edge" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="valueType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="data:UUIDType" name="type" use="required" xmlns:data="https://hoenir.space/resource/schema/data"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="propertyType">
    <xs:sequence>
      <xs:element type="data:idType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:valueType" name="value" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="propertiesType">
    <xs:sequence>
      <xs:element type="data:propertyType" name="property" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="vertexType">
    <xs:sequence>
      <xs:element type="data:idType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:edgesType" name="edges" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:weightsType" name="weights" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:propertiesType" name="properties" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="verticesType">
    <xs:sequence>
      <xs:element type="data:vertexType" name="vertex" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="graphType">
    <xs:sequence>
      <xs:element type="data:idType" name="id" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:verticesType" name="vertices" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="graphsType">
    <xs:sequence>
      <xs:element type="data:graphType" name="graph" maxOccurs="unbounded" minOccurs="0" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dataType">
    <xs:sequence>
      <xs:element type="data:baseType" name="base" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
      <xs:element type="data:graphsType" name="graphs" maxOccurs="1" minOccurs="1" xmlns:data="https://hoenir.space/resource/schema/data"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== hoenir-space/hoenir-core/example/0.0.1/xml/data_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="https://hoenir.space/resource/schema/data"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://hoenir.space/resource/schema/data ../xsd/data.xsd">
    <base type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc0993</base>
    <graphs>
        <graph>
            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099a</id>
            <vertices>
                <vertex>
                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                    <edges>
                        <edge>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <target type="b394ada4-c601-418e-a91e-ade891798c43">964e27a4-18ce-455e-9682-d0e02001adb3</target>
                            <weights>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                            </weights>
                        </edge>
                        <edge>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <target type="b394ada4-c601-418e-a91e-ade891798c43">964e27a4-18ce-455e-9682-d0e02001adb3</target>
                            <weights>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                            </weights>
                        </edge>
                    </edges>
                    <weights>
                        <weight>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value>1.0</value>
                        </weight>
                        <weight>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value>1.0</value>
                        </weight>
                    </weights>
                    <properties>
                        <property>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value type="49892732-71fd-4672-bec6-4a3ad7201c62">Bla Bla dfgdfg</value>
                        </property>
                        <property>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value type="49892732-71fd-4672-bec6-4a3ad7201c62">Bla Bla</value>
                        </property>
                    </properties>
                </vertex>
                <vertex>
                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                    <edges>
                        <edge>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <target type="b394ada4-c601-418e-a91e-ade891798c43">964e27a4-18ce-455e-9682-d0e02001adb3</target>
                            <weights>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                            </weights>
                        </edge>
                        <edge>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <target type="b394ada4-c601-418e-a91e-ade891798c43">964e27a4-18ce-455e-9682-d0e02001adb3</target>
                            <weights>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                            </weights>
                        </edge>
                    </edges>
                    <weights>
                        <weight>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value>1.0</value>
                        </weight>
                        <weight>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value>1.0</value>
                        </weight>
                    </weights>
                    <properties>
                        <property>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value type="49892732-71fd-4672-bec6-4a3ad7201c62">Bla Bla</value>
                        </property>
                        <property>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value type="49892732-71fd-4672-bec6-4a3ad7201c62">Bla Bla</value>
                        </property>
                    </properties>
                </vertex>
            </vertices>
        </graph>
        <graph>
            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
            <vertices>
                <vertex>
                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                    <edges>
                        <edge>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <target type="b394ada4-c601-418e-a91e-ade891798c43">964e27a4-18ce-455e-9682-d0e02001adb3</target>
                            <weights>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                            </weights>
                        </edge>
                        <edge>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <target type="b394ada4-c601-418e-a91e-ade891798c43">964e27a4-18ce-455e-9682-d0e02001adb3</target>
                            <weights>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                                <weight>
                                    <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                                    <value>1.0</value>
                                </weight>
                            </weights>
                        </edge>
                    </edges>
                    <weights>
                        <weight>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value>1.0</value>
                        </weight>
                        <weight>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value>1.0</value>
                        </weight>
                    </weights>
                    <properties>
                        <property>
                            <id type="3b5da256-174e-487d-9d87-5b53a816b236">8fdb9f31-d022-4b8f-a2bb-7c0f77cc099f</id>
                            <value type="49892732-71fd-4672-bec6-4a3ad7201c62">Bla Bla</value>
                        </property>
                        <property>
